### ISSUE TITLE
missing files -> will break your t3 installation

### ISSUE THREAD

**Issue by scuba303** [julianxhokaxhiu/typdom3#1]
the vendor directory of dompdf is incomplete.
at least dompdf_config.inc.php and include folder is missing.
neither ter nor githib version has the mssing files. needed to replace dompdf files with dompdf from github to make my backend working again.

**Comment by TarSzator** [comment]
Same problem.
To get your TYPO3 Backend working again you can remove the extension folder and clear the caches over the install tool.

The issue remains that these files are missing in the repo/packages.

**Comment by julianxhokaxhiu** [comment]
I've just pushed 0.0.6 to TER. Can you please try that version now?

Report back if you found any issue.

**Comment by TarSzator** [comment]
Thanks for responding.

ext/typdom3/vendor/dompdf/dompdf/dompdf_config.inc.php still missing.

**Comment by julianxhokaxhiu** [comment]
It's because I'm installing it through composer. I cannot understand why that file is still required.

**Comment by julianxhokaxhiu** [comment]
Fixed with v0.0.7 :) Just pushed to TER.

**Comment by TarSzator** [comment]
Not closed. Sorry :-)

Class 'DOMPDF' not found in ext/typdom3/Classes/TypDom3.php on line 42

**Comment by julianxhokaxhiu** [comment]
Done. Pushed 0.0.8 to the TER :D

You were right, I forgot to port the API calls to the new DomPDF 0.7 version. Now everything should be ok :) Thanks for the quick feedback!

**Comment by TarSzator** [comment]
Thanks. Works now.
